import createError from "http-errors";

// ===========================================================================================
// Get User
// ===========================================================================================

export const getUser = async (req, res, next) => {
  try {
    res.send("Habtemariam")
  } catch (error) {}
};

// ===========================================================================================
// Get Users
// ===========================================================================================

export const getnUsers = async (req, res, next) => {
  try {
  } catch (error) {}
};

// ===========================================================================================
// Delete User
// ===========================================================================================

export const deleteUser = async (req, res, next) => {
  try {
  } catch (error) {}
};

// ===========================================================================================
// Delete Users
// ===========================================================================================

export const deleteUsers = async (req, res, next) => {
    try {
    } catch (error) {}
  };
